version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"